# Meta config
meta:
  site_description: "uukiの技術ブログ"
  site_name: "uuki.dev"
  site_url: "https://uuki.dev"

# Manage config
manage:
  pages_path: "data/pages"
  contents_path: "data/docs"
  media_path: "data/images"
  google_analytics_id: "G-VZXRWE76Q9"
  github_rep_url: "https://github.com/uuki/dev/"
  email: "uuki.dev@gmail.com"
  twitter: "uuki_dev"
  github: "uuki"
