// ─────────────────────────────────────────────────────────────────────────────
// css.ts — CSS Custom Properties 出力生成
// ─────────────────────────────────────────────────────────────────────────────

import type { TokenMap, TokenName } from './palette';

const TOKEN_NAMES: TokenName[] = [
  'base-bg',
  'base-surface-1',
  'base-surface-2',
  'container-primary',
  'container-subtle',
  'text-primary',
  'text-secondary',
  'text-tertiary',
  'border-default',
  'semantic-success',
  'semantic-warning',
  'semantic-danger',
];

function varName(token: TokenName, suffix: 'light' | 'dark'): string {
  return `--color-${token}-${suffix}`;
}

function refName(token: TokenName): string {
  return `--color-${token}`;
}

export function generateCss(tokens: TokenMap): string {
  // :root { 全トークンのlightとdarkの直値 }
  const lightLines = TOKEN_NAMES.map(
    t => `  ${varName(t, 'light')}: ${tokens[t].light};`,
  ).join('\n');

  const darkLines = TOKEN_NAMES.map(
    t => `  ${varName(t, 'dark')}: ${tokens[t].dark};`,
  ).join('\n');

  // :root { --color-{token}: var(--color-{token}-light) }
  const defaultLines = TOKEN_NAMES.map(
    t => `  ${refName(t)}: var(${varName(t, 'light')});`,
  ).join('\n');

  // :root:has([data-theme="dark"]) { ... }
  const darkThemeLines = TOKEN_NAMES.map(
    t => `  ${refName(t)}: var(${varName(t, 'dark')});`,
  ).join('\n');

  return [
    '/**',
    ' * Theme colors',
    ' * Generated by uuki color token tool',
    ' */',
    ':root {',
    lightLines,
    '',
    darkLines,
    '}',
    '',
    ':root {',
    defaultLines,
    '}',
    '',
    ':root:has([data-theme="dark"]) {',
    darkThemeLines,
    '}',
  ].join('\n');
}
