import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import type { NextPage, GetStaticProps } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import config from '@/config/site'

export type PostProps = {
  title: string
  slug: string
}

const Home: NextPage<{ posts: PostProps[] }> = ({ posts }) => {
  return (
    <div>
      <p>aaa</p>
      <div>
        {posts.map((post: PostProps, index) => {
          console.log(post)
          return (
            <Link href={'/posts/' + post?.slug} passHref key={index}>
              <h2>{post?.title}</h2>
            </Link>
          )
        })}

        {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      </div>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const contentsPath = path.join(process.cwd(), 'docs')
  const files = fs.readdirSync(contentsPath)
  const posts = files
    .map((filename) => {
      if (!/\.mdx?$/.test(filename)) {
        return false
      }
      const markdownWithMeta = fs.readFileSync(path.join(process.cwd(), 'docs', filename), 'utf-8')
      const { data: frontMatter } = matter(markdownWithMeta)

      return JSON.parse(
        JSON.stringify({
          ...frontMatter,
          slug: filename.split('.')[0],
        })
      )
    })
    .filter(Boolean)
  return {
    props: {
      posts,
    },
  }
}

export default Home
