zenn:
  name: Zenn
  url: https://zenn.dev
  logo: /static/images/logo-zenn.svg
hatena:
  name: Hatena
  url: https://hatenablog.com
  logo: /static/images/logo-hatenablog.svg
qiita:
  name: Qiita
  url: https://qiita.com
  logo: "/static/images/logo-qiita.svg"
uuki:
  name: Blog
  url: https://uuki.dev
  logo: /static/images/logo-badge.png