/* eslint-disable */
/* prettier-ignore */

/**
 * Placeholder — auto-generated by @0no-co/graphqlsp after schema download.
 *
 * To generate the real file:
 *   1. npx gql.tada generate schema \
 *        --header "Authorization: bearer $GITHUB_TOKEN" \
 *        --output src/graphql/github/schema.graphql \
 *        https://api.github.com/graphql
 *   2. npx gql.tada generate output
 *
 * Until then, query result types are inferred as `unknown`.
 */
export type introspection = {
  query: 'Query';
  mutation: never;
  subscription: never;
  types: {};
};
