import { initGraphQLTada } from 'gql.tada';
// graphql-env.d.ts is auto-generated by @0no-co/graphqlsp.
// To generate: npx gql.tada generate schema --header "Authorization: bearer $GITHUB_TOKEN" \
//   --output src/graphql/github/schema.graphql https://api.github.com/graphql
// Then: npx gql.tada generate output
import type { introspection } from './graphql-env.d.ts';

export const graphql = initGraphQLTada<{
  introspection: introspection;
}>();

export type { FragmentOf, ResultOf, VariablesOf } from 'gql.tada';
